image: registry.gitlab.com/ignitionrobotics/web/images/web-server-pipelines

variables:
  PKG_NAME: gitlab.com/ignitionrobotics/web/web-server
  MYSQL_DATABASE: "ignition_test"
  MYSQL_ROOT_PASSWORD: "root"

##########################################################
# Stages

stages:
  - formatting
  - linting
  - testing
  - building
  - deploying

##########################################################
# Formatting stage

format:
  stage: formatting
  script:
    - go fmt $(go list ./...)

##########################################################
# Linting stage

lint:
  stage: linting
  script:
    - /root/go/bin/golangci-lint run

##########################################################
# Testing stage

test:
  stage: testing
  script:
    - go test $(go list ./...)
  services:
    - mysql:5.7
  environment:
    name: testing

##########################################################
# Building stage

build:
  stage: building
  script:
    - go build

##########################################################
# Deploying stage

staging:
  image: python:3.5
  stage: deploying
  dependencies:
    - build
  script:
    - zip -r artifact.zip * .ebextensions 
    - python beanstalk_deploy.py
  environment:
    name: staging
    url: https://ignitionrobotics-staging.us-east-1.elasticbeanstalk.com/1.0
  only:
    - "/^release\\/.*$/"
    - develop
  when: manual

production:
  image: python:3.5
  stage: deploying
  dependencies:
    - build
  script:
    - zip -r artifact.zip * .ebextensions
    - python beanstalk_deploy.py
  environment:
    name: production
    url: https://ignitionrobotics-production.us-east-1.elasticbeanstalk.com/1.0
  only:
    - master
  when: manual
