image: registry.gitlab.com/ignitionrobotics/web/images/web-server-pipelines

variables:
  PKG_NAME: gitlab.com/ignitionrobotics/web/web-server
  MYSQL_DATABASE: "ignition_test"
  MYSQL_ROOT_PASSWORD: "root"

##########################################################
# Stages

stages:
  - format
  - test
  - building
  - deploying

##########################################################
# Format stage

fmt:
  stage: format
  script:
    - go fmt $(go list ./...)

lint:
  stage: format
  before_script:
    - $GOPATH/bin/golangci-lint --version
  script:
    - $GOPATH/bin/golangci-lint run --skip-dirs vcs --disable-all  --enable=golint --enable=varcheck --enable=maligned --enable=interfacer --timeout=2m0s
  allow_failure: true

##########################################################
# Testing stage

test:
  stage: test
  script:
    - go test $(go list ./...)
  services:
    - mysql:5.7
  environment:
    name: testing

##########################################################
# Building stage

build:
  stage: building
  script:
    - go build

##########################################################
# Deploying stage

staging:
  image: registry.gitlab.com/ignitionrobotics/web/images/web-server-pipelines
  stage: deploying
  dependencies:
    - build
  script:
    - zip -r artifact.zip * .ebextensions 
    - python beanstalk_deploy.py
  environment:
    name: staging
    url: https://ignitionrobotics-staging.us-east-1.elasticbeanstalk.com/1.0
  only:
    - "/^release\\/.*$/"
    - develop
  when: manual

production:
  image: registry.gitlab.com/ignitionrobotics/web/images/web-server-pipelines
  stage: deploying
  dependencies:
    - build
  script:
    - zip -r artifact.zip * .ebextensions
    - python beanstalk_deploy.py
  environment:
    name: production
    url: https://ignitionrobotics-production.us-east-1.elasticbeanstalk.com/1.0
  only:
    - master
  when: manual
