name: deploy

# Controls when the workflow will run
on:
  push:
    branches: [ staging, production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  staging-deploy:
    if: github.ref == 'refs/heads/staging'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: staging
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      API_HOST:  ${{ secrets.API_HOST }}
      APP_HOST: ${{ secrets.APP_HOST }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

        # - name: Test
        #   run: go test -v ./...

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
